options:
  logging: CLOUD_LOGGING_ONLY

steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'us-central1-docker.pkg.dev/finalproject-1234567/my-repo/spam-classifier-api:$SHORT_SHA'
      - '.'
  
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'us-central1-docker.pkg.dev/finalproject-1234567/my-repo/spam-classifier-api:$SHORT_SHA'
  
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'spam-classifier-api'
      - '--image=us-central1-docker.pkg.dev/finalproject-1234567/my-repo/spam-classifier-api:$SHORT_SHA'
      - '--region=us-central1'
      - '--platform=managed'
      - '--allow-unauthenticated'
    serviceAccount: 'cloud-build-sa@finalproject-1234567.iam.gserviceaccount.com'

images:
  - 'us-central1-docker.pkg.dev/finalproject-1234567/my-repo/spam-classifier-api:$SHORT_SHA'
