steps:
  # Step 1: Authenticate with Artifact Registry
  - name: 'gcr.io/cloud-builders/gcloud'
    id: 'Authenticate with Artifact Registry'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gcloud auth configure-docker us-central1-docker.pkg.dev

  # Step 2: Build Docker Image
  - name: 'gcr.io/cloud-builders/docker'
    id: 'Build Docker Image'
    args:
      - 'build'
      - '-t'
      - 'us-central1-docker.pkg.dev/finalproject-1234567/my-repo/spam-classifier-api:$_SHORT_SHA'
      - 'api/'  # Change if your Dockerfile is elsewhere

  # Step 3: Push Docker Image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    id: 'Push Docker Image'
    args:
      - 'push'
      - 'us-central1-docker.pkg.dev/finalproject-1234567/my-repo/spam-classifier-api:$_SHORT_SHA'

  # Step 4: Deploy Docker Image to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    id: 'Deploy to Cloud Run'
    args:
      - 'run'
      - 'deploy'
      - 'spam-classifier-api'
      - '--image'
      - 'us-central1-docker.pkg.dev/finalproject-1234567/my-repo/spam-classifier-api:$_SHORT_SHA'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'

  # Step 5: Notify Build Success
  - name: 'gcr.io/cloud-builders/gcloud'
    id: 'Notify Build Success'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "Docker Image Built & Pushed: us-central1-docker.pkg.dev/finalproject-1234567/my-repo/spam-classifier-api:$_SHORT_SHA"
        echo "Cloud Run Service Deployed: https://spam-classifier-api-888676141442.us-central1.run.app"

images:
  - 'us-central1-docker.pkg.dev/finalproject-1234567/my-repo/spam-classifier-api:$_SHORT_SHA'

options:
  logging: CLOUD_LOGGING_ONLY
  build:
    logs_bucket: 'gs://final-central-staging-output/'  # Specify your logs bucket here

substitutions:
  _SHORT_SHA: ${SHORT_SHA:-latest}
