display_name: "my-training-job"
job_spec:
  worker_pool_specs:
  - machine_spec:
      machine_type: n1-standard-4
    disk_spec:
      boot_disk_type: pd-ssd
      boot_disk_size_gb: 100
    container_spec:
      image_uri: gcr.io/deeplearning-platform-release/base-cpu
      args:
      - --train-script-path=gs://groupfinal/train_script.tar.gz
